#ifndef _PPCS_ERROR___INC_H_
#define _PPCS_ERROR___INC_H_

#define ERROR_PPCS_SUCCESSFUL						(0)
#define ERROR_PPCS_NOT_INITIALIZED					(-1)
#define ERROR_PPCS_ALREADY_INITIALIZED				(-2)
#define ERROR_PPCS_TIME_OUT							(-3)
#define ERROR_PPCS_INVALID_ID						(-4)
#define ERROR_PPCS_INVALID_PARAMETER				(-5)
#define ERROR_PPCS_DEVICE_NOT_ONLINE				(-6)
#define ERROR_PPCS_FAIL_TO_RESOLVE_NAME				(-7)
#define ERROR_PPCS_INVALID_PREFIX					(-8)
#define ERROR_PPCS_ID_OUT_OF_DATE					(-9)
#define ERROR_PPCS_NO_RELAY_SERVER_AVAILABLE		(-10)
#define ERROR_PPCS_INVALID_SESSION_HANDLE			(-11)
#define ERROR_PPCS_SESSION_CLOSED_REMOTE			(-12)
#define ERROR_PPCS_SESSION_CLOSED_TIMEOUT			(-13)
#define ERROR_PPCS_SESSION_CLOSED_CALLED			(-14)
#define ERROR_PPCS_REMOTE_SITE_BUFFER_FULL			(-15)
#define ERROR_PPCS_USER_LISTEN_BREAK				(-16)
#define ERROR_PPCS_MAX_SESSION						(-17)
#define ERROR_PPCS_UDP_PORT_BIND_FAILED				(-18)
#define ERROR_PPCS_USER_CONNECT_BREAK				(-19)
#define ERROR_PPCS_SESSION_CLOSED_INSUFFICIENT_MEMORY	(-20)
#define ERROR_PPCS_INVALID_APILICENSE				(-21)
#define ERROR_PPCS_FAIL_TO_CREATE_THREAD			(-22)


#define ERROR_NULL_POINT                            (-100)
#define ERROR_HAVE_CONNECT                          (-101)
#define ERROR_MAX_HUB_CONNECT_NUM                   (-102)
#define ERROR_INVALID_COMMAND                       (-103)
#define ERROR_INVALID_ACCOUNT                       (-104)
#define ERROR_WRITE_FLASH                           (-105)
#define ERROR_NOT_FIND_DEV                          (-106)
#define ERROR_INVALID_PARAM_LEN                     (-107)
#define ERROR_WAIT_TIMEOUT                          (-108)
#define ERROR_DEV_OFFLINE                           (-109)
#define ERROR_INVALID_PARAM                         (-110)
#define ERROR_OPEN_FILE_FAIL                        (-111)
#define ERROR_HUB_UPDATEING                         (-112)
#define ERROR_DEV_UPDATEING                         (-113)
#define ERROR_DEV_BUSY                              (-114)
#define ERROR_NOT_FACE                              (-115)


#define AS_HTTP_OPER_SUCESS                         (0)
#define AS_HTTP_200                                 (200)    
#define AS_HTTP_HUB_NO_BIND                         (20003)
#define AS_HTTP_HUB_BIND_OTHER                      (20020)              

#endif //// #ifndef _PPCS_ERROR___INC_H_
